v1.1.0
- Added `-e` argument to exclude files / folders when generating the backup file.
- Added `-v` argument for verbose output.

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -2,7 +2,7 @@
 ## ------------------------------------
 ##  Made By: Michael Yochpaz (C) 2020
 ##  https://github.com/MichaelYochpaz/Backup-Script
-##  Version: 1.0
+##  Version: 1.1.0
 ##  License: GPLv3
 ## ------------------------------------
 ## -------------- Usage ---------------
@@ -13,27 +13,32 @@
 ##  - In order to use the upload feature, rclone must be installed and have at least one cloud service setup in config.
 ## ------------------------------------
 ##
-##  Usage: backup [-n <name>] [-s <path>] [-u <path>] [-r] <path-to-backup>
+##  Usage: backup [-n <name>] [-s <path>] [-e <pattern>]... [-u <path>] [-r] [-v] <path-to-backup>
 ##
 ##  Options:
-##    -n <name>  Sets the tar.gz file name [default: "backup"]
-##    -s <path>  Path to which the generated backup file will be saved to [default: current working directory]
-##    -u <path>  rclone path to which the backup file will be uploaded to (not providing one will skip the upload process)
-##    -r         Remove local copy of backup file after it's been uploaded
+##    -n <name>     Sets the tar.gz file name [default: "backup"]
+##    -s <path>     Path to which the generated backup file will be saved to [default: current working directory]
+##    -e <pattern>  Exclude a pattern (specific files / folders) from being backed up
+##    -u <path>     rclone path to which the backup file will be uploaded to (not providing one will skip the upload process)
+##    -r            Removes local copy of backup file after it's been uploaded
+##    -v            Runs tar and rclone using the '-v' option
 ##
 ##  Commands:
-##    -h         Displays this help and exists.
+##    -h            Displays this help and exists.
 ##
 ##  Examples:
 ##    backup "/home/user/important_stuff"
-##    backup -n "important-stuff-backup" -s "/home/user/backups" -u "GDrive:/Backups" -r "/home/user/important_stuff/"
+##    
+##    backup -n \"important-stuff-backup\" -s \"/home/user/backups\" -e \"*.pdf\" -e \"important_stuff/dont_backup_this_folder\" \"/home/user/important_stuff/\""
 ##
 ## --------- Configuration ------------
 BACKUP_NAME="backup" # backup file name. date will be added to file name after this string
 BACKUP_FOLDER="" # folder to backup (full path)
+EXCLUDES=() # array to store exclusion patterns. example: ("*.mkv" "*.pdf" "/home/user/important_stuff/no_backup_folder")
 SAVE_FOLDER="$PWD" # folder to save backup file to (full path)
 RCLONE_FOLDER="" # path to rclone folder to which file will be uploaded to. leave empty to skip upload
 REMOVE_LOCAL=false # remove local backup file after upload
+VERBOSE=false # print extra information and use -v option on tar & rclone
 ## ------------------------------------
 
 usage() { echo "Usage: $(basename $0) [-h] [-n <name>] [-s <path>] [-u <path>] [-r] <path>
@@ -43,13 +48,16 @@ ERROR=false # sets to true when there's an error for final exit code
 C0='\033[0m' # ANSI - no color
 C1='\033[0;32m' # ANSI - success - green
 C2='\033[1;31m' # ANSI - error - red
-C3='\033[0;36m' # ANSI - information - orange
-C4='\033[0;33m' # ANSI - variables/paths - cyan
+C3='\033[0;36m' # ANSI - information - cyan
+C4='\033[0;33m' # ANSI - variables/paths - orange
 
-while getopts ":n:s:u:rh" arg; do
+while getopts ":n:e:s:u:rvh" arg; do
   case $arg in
     n)
       BACKUP_NAME=${OPTARG}
+      ;;
+    e)
+      EXCLUDES+=("${OPTARG}")
       ;;
     s)
       SAVE_FOLDER=${OPTARG}
@@ -60,20 +68,26 @@ while getopts ":n:s:u:rh" arg; do
     r)
       REMOVE_LOCAL=true
       ;;
+    v)
+      VERBOSE=true
+      ;;
     h)
-      echo " Usage: $(basename $0) [-n <name>] [-s <path>] [-u <path>] [-r] <path-to-backup>
+      echo " Usage: $(basename $0) [-n <name>] [-e <pattern>]... [-s <path>] [-u <path>] [-r] <path-to-backup>
  Options:
-   -n <name>  Sets the tar.gz file name (date is added) [default: "backup"]
-   -s <path>  Path to which the generated backup file will be saved to [default: current working directory]
-   -u <path>  rclone path to which the backup file will be uploaded to (not providing one will skip the upload process)
-   -r         Remove local copy of backup file after it's been uploaded
+   -n <name>     Sets the tar.gz file name (date is added) [default: "backup"]
+   -s <path>     Path to which the generated backup file will be saved to [default: current working directory]
+   -e <pattern>  Exclude a pattern (specific files / folders) from being backed up
+   -u <path>     rclone path to which the backup file will be uploaded to (not providing one will skip the upload process)
+   -r            Removes local copy of backup file after it's been uploaded
+   -v            Runs tar and rclone using the '-v' option
 
  Commands:
-   -h         Displays this help and exists.
+   -h            Displays this help and exists.
 
  Examples:
    $(basename $0) \"/home/user/important_stuff\"
-   $(basename $0) -n \"important-stuff-backup\" -s \"/home/user/backups\" -u \"GDrive:/Backups\" -r \"/home/user/important_stuff\""
+   $(basename $0) backup -u \"GDrive:/Backups\" -r \"/home/user/important_stuff/\"
+   $(basename $0) -n \"important-stuff-backup\" -s \"/home/user/backups\" -e \"*.pdf\" -e \"important_stuff/dont_backup_this_folder\" \"/home/user/important_stuff/\""
       exit 0
       ;;
     *)
@@ -82,23 +96,26 @@ while getopts ":n:s:u:rh" arg; do
   esac
 done
 
-if [[ -n ${@:$OPTIND:1} ]]; then BACKUP_FOLDER=${@:$OPTIND:1}; fi # positional argument - the folder that's going to be backed-up
-
-if [ -z $BACKUP_FOLDER ]; then usage; fi # if no backup folder was chosen
-
-if [ ! -d $BACKUP_FOLDER ]; then # if BACKUP_FOLDER path doesn't exist
+# positional argument - the folder that's going to be backed-up
+if [[ -n "${@:$OPTIND:1}" ]]; then BACKUP_FOLDER=${@:$OPTIND:1}; fi
+# if no backup folder was chosen, show usage
+if [ -z "$BACKUP_FOLDER" ]; then usage; fi 
+# if BACKUP_FOLDER path doesn't exist, show error and exit
+if [ ! -d $BACKUP_FOLDER ]; then 
   echo -e "${C2}Folder ${C4}$BACKUP_FOLDER ${C2}not found${C0}"
   exit 1
 fi
-
-if [ ! -d $SAVE_FOLDER ]; then # if SAVE_FOLDER path doesn't exist
+# if SAVE_FOLDER path doesn't exist, show error and exit
+if [ ! -d $SAVE_FOLDER ]; then 
   echo -e "${C2}Folder ${C4}$SAVE_FOLDER ${C2}not found${C0}"
   exit 1
 fi
-
-if [ "${SAVE_FOLDER: -1}" = "/" ]; then SAVE_FOLDER=${SAVE_FOLDER%?}; fi # if SAVE_FOLDER path ends with a '/', remove it
-
-if [ "$REMOVE_LOCAL" = true ] && [ -z $RCLONE_FOLDER ]; then # if REMOVE_LOCAL is set to true, but rclone upload is not used.
+# if BACKUP_FOLDER path ends with a '/', remove it
+if [ "${BACKUP_FOLDER: -1}" = "/" ]; then BACKUP_FOLDER=${BACKUP_FOLDER%?}; fi 
+# if SAVE_FOLDER path ends with a '/', remove it
+if [ "${SAVE_FOLDER: -1}" = "/" ]; then SAVE_FOLDER=${SAVE_FOLDER%?}; fi
+ # if REMOVE_LOCAL is set to true, but rclone upload is not used, show a warning.
+if [ "$REMOVE_LOCAL" = true ] && [ -z "$RCLONE_FOLDER" ]; then
   read -p "WARNING: '-r' argument to remove local backup file was used,
   but no rclone path to upload backup flie to beforehand is set.
   This will result in generating a backup file and deleting it after without it being uploaded anywhere.
@@ -108,27 +125,42 @@ if [ "$REMOVE_LOCAL" = true ] && [ -z $RCLONE_FOLDER ]; then # if REMOVE_LOCAL i
   if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit 0; fi
 fi
 
+# ----- tar -----
 echo -e "$(date +"%Y/%m/%d %T") ${C3}Generating tar.gz file"${C0}
 FILENAME="${BACKUP_NAME}-$(date +%FT%H%M).tar.gz"
-tar -czf "$SAVE_FOLDER/$FILENAME" -C "$BACKUP_FOLDER/.." "$(basename "$BACKUP_FOLDER")"
+# generate a temporary file to store EXCLUDES in
+EXCLUEDS_FILE=$(mktemp /tmp/backup.XXXXXX.txt) 
+if [ ! ${#EXCLUDES[@]} -eq 0 ]; then printf "%s\n" "${EXCLUDES[@]}" > "$EXCLUEDS_FILE"; fi
 
-if [ "$?" = 0 ]; then # tar commmand ran successfully (exit code = 0)
+# run tar with or without '-v', according to VERBOSE value
+if [ "$VERBOSE" = true ]; then tar -cvzf "$SAVE_FOLDER/$FILENAME" -C "$BACKUP_FOLDER/.." -X $EXCLUEDS_FILE "$(basename "$BACKUP_FOLDER")"; \
+else tar -czf "$SAVE_FOLDER/$FILENAME" -C "$BACKUP_FOLDER/.." -X $EXCLUEDS_FILE "$(basename "$BACKUP_FOLDER")"; fi
+
+# tar commmand ran successfully (exit code = 0)
+if [ "$?" = 0 ]; then
   echo -e "$(date +"%Y/%m/%d %T") ${C1}Backup file generated and saved successfully to ${C4}$SAVE_FOLDER/$FILENAME ($(du -h "$SAVE_FOLDER/$FILENAME" | cut -f1))${C0}"
-
-else #tar commmand didnt ran successfully (exit code != 0)
+# tar commmand didn't run successfully (exit code != 0)
+else 
   echo -e "$(date +"%Y/%m/%d %T") ${C2}Backup file generation failed${C0}"
-  rm "$SAVE_FOLDER/$FILENAME"
-  exit 1
+# remove temporary file
+rm $EXCLUEDS_FILE
+# if tar file was generated during the failed tar process, remove it
+  if [ -f "$SAVE_FOLDER/$FILENAME" ]; then
+    rm "$SAVE_FOLDER/$FILENAME"
+    exit 1
+  fi
 fi
 
-if [ -n $RCLONE_FOLDER ]; then
+# ----- rclone -----
+if [ -n "$RCLONE_FOLDER" ]; then
   echo -e "$(date +"%Y/%m/%d %T") ${C3}Uploading backup file to ${C4}$RCLONE_FOLDER${C0}"
-  rclone copy "$SAVE_FOLDER/$FILENAME" "$RCLONE_FOLDER"
-
-  if [ "$?" = 0 ]; then # rclone commmand ran successfully (exit code = 0)
+# run rclone with or without '-v', according to VERBOSE value
+  if [ "$VERBOSE" = true ]; then rclone copy "$SAVE_FOLDER/$FILENAME" -v "$RCLONE_FOLDER"; else rclone copy "$SAVE_FOLDER/$FILENAME" "$RCLONE_FOLDER"; fi
+# rclone commmand ran successfully (exit code = 0)
+  if [ "$?" = 0 ]; then
     echo -e "$(date +"%Y/%m/%d %T") ${C1}Backup file uploaded successfully to ${C4}$RCLONE_FOLDER${C0}"
-
-  else # rclone command didn't ran successfully (exit code != 0)
+# rclone command didn't run successfully (exit code != 0)
+  else
     ERROR=true
     echo -e "$(date +"%Y/%m/%d %T") ${C2}Upload failed${C0}"
 
@@ -142,12 +174,13 @@ if [ -n $RCLONE_FOLDER ]; then
     fi
   fi
 fi
-
+# remove local backup if REMOVE_LOCAL setting used
 if [ "$REMOVE_LOCAL" = true ]; then
   rm "$SAVE_FOLDER/$FILENAME"
   echo -e "$(date +"%Y/%m/%d %T") ${C1}Local file removed${C0}"
 fi
 
+# print and exit using correct code according to ERROR's value
 if [ "$ERROR" = false ]; then
   echo -e "$(date +"%Y/%m/%d %T") ${C1}Script finished successfully${C0}"
   exit 0;
